##################################################

# Run Mr Coxall's Super Linter against code base #

##################################################



---

name: Mr Coxall's Super Linter



on: [push, pull_request]



jobs:

  run-linters:

    name: GitHub's Super Linter

    runs-on: ubuntu-latest



    steps:

      - name: Check out Git repository

        uses: actions/checkout@master



      - name: Prettify code

        uses: creyD/prettier_action@master

        with:

          # run Prettier and change any code that needs fixing, before next section

          prettier_options: --write **/*.{html,css,js,md}

        

      - name: Run GitHub Super Linter

        uses: github/super-linter@master

        env:

          VALIDATE_ALL_CODEBASE: true

          VALIDATE_CLANG_FORMAT: false

          VALIDATE_JAVASCRIPT_STANDARD: false

          VALIDATE_PYTHON_FLAKE8: false

          VALIDATE_GITLEAKS: false # for secrets detection

          VALIDATE_JSCPD: false # for copy and paste detection

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
